sudo: false
language: node_js
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
notifications:
  email: false
node_js:
  - stable
before_install:
  - npm i -g npm@^6.13.6
script:
  - npm run test:single
after_success:
  - npm run semantic-release
